### PR TITLE
Adding some Spanish banks and Halifax from UK

### PR DESCRIPTION
**Pull request by osroca**
This is what I have for now. Added, among others, BBVA, Banco Santander, CaixaBank, Banco Sabadell, and ING.
I'll continue adding more banks as a get more bank accounts to extract the needed info. I'll also work on the new Exceptions as discussed in #19.

I would need this merged and released to use the new banks data in my project. Unless there is an easy way to use a tarball version from my own repo. I used to do so via `dependency_links` but it looks like pbr doesn't play well with that snapshot-like option. What I have done is to tag my update as 2020.01.1 in my repo and setup my `dependency_links` to point to my repo's tarball (`https://github.com/osroca/schwifty/tarball/2020.01.1#egg=schwifty-2020.01.1`). This caused the following error when installing my project:

```
  File "/private/var/folders/z_/ll7j31r11p37z687bk0w7bs80000gn/T/easy_install-id3gs88l/osroca-schwifty-2a88b09/.eggs/pbr-5.4.4-py3.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/private/var/folders/z_/ll7j31r11p37z687bk0w7bs80000gn/T/easy_install-id3gs88l/osroca-schwifty-2a88b09/.eggs/pbr-5.4.4-py3.7.egg/pbr/packaging.py", line 876, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name schwifty was given, but was not able to be found.
error: Setup script exited with error in setup command: Error parsing /private/var/folders/z_/ll7j31r11p37z687bk0w7bs80000gn/T/easy_install-id3gs88l/osroca-schwifty-2a88b09/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name schwifty was given, but was not able to be found.
```

It's a bit embarrassing, but I'm not familiar enough to pbr.

### CODE REVIEW

**Comment by mdomke** [comment]
It's good that were starting to get some non-german banks into schwifty! I think however that I have to add a mechanism first to deal with different kind of data sources. What I mean is that the current `bank-registry.json` is a generated file, but now there is manually curated data that should not be overwritten by the generator script. I can work on a solution for that tomorrow.

Regarding your installation problem. Are you trying to install your local version of the library inside a virtual environment? You can always do `pip install -e .` (or even without the `-e` option) from the repository root to install the package into your current environment. If you want to create a distributable package you can do `pip wheel --no-deps .` (or `python setup.py bdist_wheel`) and you'll get a wheel that you can install elsewhere.

**Comment by osroca** [comment]
Thanks for your quick reply. Let me know if I have to do any adaptation in this PR to match the new implementation about the mechanism to deal with different data sources.

Regarding the installation problem. It's most related that I would like to prevent to have to install manually this library when I install the main project that depends on it. I'll manage it until my PR is merged. 

Thanks!

**Comment by mdomke** [comment]
Alright… I added a change to the bank and IBAN registries. There are now two directories `bank_registry` and `iban_registry` within the `schwifty`-package which contain a number of JSON-files. These files are loaded on package import. It is now possible to have generated files and additionally manually curated data, which is not overwritten by the generator scripts. You would have to take the bank data that you gathered and put them into the files
* `bank_registry/manual_es.json`
* `bank_registry/manual_gb.json`
respectively. The `manual_`-prefix is purely conventional and I might come up with a better naming scheme in the future, but this should work for now. Please give me feedback if you encounter any problems. You will have to rebase your changes onto the current state of the master branch (or merge the current master into your branch).

**Comment by mdomke** [comment]
@osroca if you want I can also take it from here and include your manually crafted entries into the registry, what do you say?

**Comment by osroca** [comment]
@mdomke sorry about that, I didn't notice your previous message. 
Sure! I'll take a look at your changes and I'll update this PR right away.
Thanks again for working on this.

**Comment by osroca** [comment]
Update the PR adding two new `manual_*.json` files. The one for GB has only one entry for now though.

**Pull request merged**
