### PR TITLE
Add 9 French banks

### PR DESCRIPTION
**Pull request by aktiur**
I used to maintain a list of French banks before finding this package, and there were 9 I've seen in the wild that weren't in this project.

I'm not sure how the "primary" parameter should be set, please tell me if I've made a mistake.

### CODE REVIEW

**Comment by Natim** [comment]
What about those one? Should we add them as well?

```
Banque Marze 
Devengo
Banque des Territoires 
Crédit Municipal de Roubaix 
Crédit Municipal de Lyon 
Crédit Municipal de Boulogne sur Mer 
Crédit Municipal de Toulon 
Crédit Municipal de Nîmes 
Crédit Municipal de Nantes 
Louvre Banque Privée (ex BPE Banque Privée) 
Oney - Banque Accord 
Crédit Maritime Grand Ouest 
Crédit Maritime Atlantique 
Crédit Maritime Littoral du Sud-Ouest 
PayPal 
Rothschild Martin Maurel 
Yomoni 
Oney Banque 
American Express 
Finom 
```

**Review by Natim — APPROVED** [review]

**Comment by aktiur** [comment]
> What about those one? Should we add them as well?
> 
> ```
> Banque Marze 
> Devengo
> Banque des Territoires 
> Crédit Municipal de Roubaix 
> Crédit Municipal de Lyon 
> Crédit Municipal de Boulogne sur Mer 
> Crédit Municipal de Toulon 
> Crédit Municipal de Nîmes 
> Crédit Municipal de Nantes 
> Louvre Banque Privée (ex BPE Banque Privée) 
> Oney - Banque Accord 
> Crédit Maritime Grand Ouest 
> Crédit Maritime Atlantique 
> Crédit Maritime Littoral du Sud-Ouest 
> PayPal 
> Rothschild Martin Maurel 
> Yomoni 
> Oney Banque 
> American Express 
> Finom 
> ```

Where did you find that list? I never found a complete list of french banks with both CIB and BIC.

**Comment by mdomke** [comment]
@aktiur Thanks for the added banks! The `bank_code` has to be a string even though it is numeric. That's the reason why the tests are failing.

**Comment by mdomke** [comment]
@aktiur I'm closing this merge-request, since @Natim took the liberty to expand on it in #229, which just got merged. Thanks for your support!

**Pull request closed without merging**
