### PR TITLE
Add BIC registries

### PR DESCRIPTION
**Pull request by taoisu**
Running a script to call 3rd party apis to get the registries for missing countries.

The script is excluded from this pr, if needed I can check-in as a separate pr.

### CODE REVIEW

**Comment by taoisu** [comment]
Hi @mdomke, thanks for the great repo, I'd like to add a few bic entries here if that's ok with you.

**Comment by mdomke** [comment]
Hi @taoisu, thank you for your contribution, and sorry for the late reply. Would it be possible that you also add the scripts that you used to generate the registry files? That would allow me to update the data from time to time.

**Comment by mdomke** [comment]
@taoisu would you be able to add the scripts alongside the generated registry entries? That would be helpful!

**Comment by mdomke** [comment]
@taoisu never mind, I found the script in your commit history 😉

**Pull request merged**
