### PR TITLE
 Sort bank registry for Italy and add new banks

### PR DESCRIPTION
**Pull request by dennisxtria**
In light of new [commit](https://github.com/mdomke/schwifty/commit/f25956c1ffdeaf065287d2bf65ef1efbeeed6be9) which removed manual_it.json, I've added banks that were removed and sort fields and the whole registry by bank_code key to make it easier for future updates
cc @mdomke
edit: closed #156 to also switch master to main as default branch

### CODE REVIEW

**Comment by mdomke** [comment]
Hey @dennisxtria!
Thank you for the additions to the registry. Since the Italian bank registry is now generated, it does not make any sense to manually add entries to the `generated_it.json` file. You can however create a `manual_it.json` file alongside the generated one with the entries that you are missing.

**Comment by mdomke** [comment]
@dennisxtria do you think it is possible to extract the additional Italian banks into a `manual_it.json` file?

**Comment by dennisxtria** [comment]
> @dennisxtria do you think it is possible to extract the additional Italian banks into a `manual_it.json` file?

Yes of course! I'll get on it tomorrow if that's ok.

**Comment by dennisxtria** [comment]
> @dennisxtria I don't want to put stress on you, but if you could create this `manual_it.json` we can include this in the next release 

Hello @mdomke 

Apologies for the late reply, I will have it ready tonight if that's ok.

**Comment by dennisxtria** [comment]
heads up @mdomke working on it now

**Comment by dennisxtria** [comment]
@mdomke fixed, should be 3 new commits with today's date, can you take a look please?

**Pull request merged**
